"""
Concrete implementations of backend services.

This module provides concrete implementations of the service interfaces.
"""
from typing import Any, Dict, List, Optional, Union
from pathlib import Path
import json
import csv
import logging
from dataclasses import asdict

from transistordatabase.backend.services import (
    IExportService, IComparisonService, IValidationService,
    IPlottingService, ICalculationService
)
from transistordatabase.core.models import Transistor


logger = logging.getLogger(__name__)


class ExportService(IExportService):
    """Service for exporting transistor data to various formats."""
    
    def export_to_json(self, transistor: Transistor, filepath: Path) -> bool:
        """Export transistor to JSON format."""
        try:
            # Convert transistor to dictionary
            data = asdict(transistor)
            
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
            
            logger.info(f"Exported transistor to JSON: {filepath}")
            return True
            
        except Exception as e:
            logger.error(f"Error exporting to JSON: {e}")
            return False
    
    def export_to_csv(self, transistors: List[Transistor], filepath: Path) -> bool:
        """Export transistors to CSV format."""
        try:
            if not transistors:
                logger.warning("No transistors to export")
                return False
            
            # Define CSV headers
            headers = [
                'name', 'type', 'manufacturer', 'v_abs_max', 'i_abs_max',
                'i_cont', 't_j_max', 'r_th_cs', 'housing_type', 'comment'
            ]
            
            with open(filepath, 'w', newline='', encoding='utf-8') as f:
                writer = csv.DictWriter(f, fieldnames=headers)
                writer.writeheader()
                
                for transistor in transistors:
                    row = {
                        'name': transistor.name,
                        'type': transistor.metadata.type if transistor.metadata else '',
                        'manufacturer': transistor.metadata.manufacturer if transistor.metadata else '',
                        'v_abs_max': transistor.electrical.v_abs_max if transistor.electrical else 0,
                        'i_abs_max': transistor.electrical.i_abs_max if transistor.electrical else 0,
                        'i_cont': transistor.electrical.i_cont if transistor.electrical else 0,
                        't_j_max': transistor.thermal.t_j_max if transistor.thermal else 0,
                        'r_th_cs': transistor.thermal.r_th_cs if transistor.thermal else 0,
                        'housing_type': transistor.metadata.housing_type if transistor.metadata else '',
                        'comment': transistor.metadata.comment if transistor.metadata else ''
                    }
                    writer.writerow(row)
            
            logger.info(f"Exported {len(transistors)} transistors to CSV: {filepath}")
            return True
            
        except Exception as e:
            logger.error(f"Error exporting to CSV: {e}")
            return False
    
    def export_to_spice(self, transistor: Transistor, filepath: Path) -> bool:
        """Export transistor model to SPICE format."""
        try:
            # Generate basic SPICE model
            spice_content = self._generate_spice_model(transistor)
            
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(spice_content)
            
            logger.info(f"Exported transistor to SPICE: {filepath}")
            return True
            
        except Exception as e:
            logger.error(f"Error exporting to SPICE: {e}")
            return False
    
    def _generate_spice_model(self, transistor: Transistor) -> str:
        """Generate SPICE model content."""
        name = transistor.name.replace(' ', '_')
        
        spice_lines = [
            f"* SPICE model for {transistor.name}",
            f"* Generated by Transistor Database",
            f"*",
            f".model {name} NPN (",
        ]
        
        # Add electrical parameters if available
        if transistor.electrical:
            if transistor.electrical.v_abs_max:
                spice_lines.append(f"+ BV={transistor.electrical.v_abs_max}")
            if transistor.electrical.i_abs_max:
                spice_lines.append(f"+ IS={transistor.electrical.i_abs_max * 1e-6}")
        
        spice_lines.append("+ )")
        spice_lines.append("")
        spice_lines.append(f"* Model: {transistor.name}")
        
        if transistor.metadata:
            spice_lines.append(f"* Manufacturer: {transistor.metadata.manufacturer or 'Unknown'}")
            spice_lines.append(f"* Type: {transistor.metadata.type or 'Unknown'}")
        
        return "\n".join(spice_lines)


class ComparisonService(IComparisonService):
    """Service for comparing transistors."""
    
    def compare_transistors(self, transistors: List[Transistor]) -> Dict[str, Any]:
        """Compare multiple transistors."""
        if len(transistors) < 2:
            return {'error': 'At least 2 transistors required for comparison'}
        
        comparison = {
            'transistor_count': len(transistors),
            'transistors': [t.name for t in transistors],
            'electrical_comparison': self._compare_electrical(transistors),
            'thermal_comparison': self._compare_thermal(transistors),
            'metadata_comparison': self._compare_metadata(transistors)
        }
        
        return comparison
    
    def _compare_electrical(self, transistors: List[Transistor]) -> Dict[str, Any]:
        """Compare electrical characteristics."""
        v_max_values = []
        i_max_values = []
        i_cont_values = []
        
        for transistor in transistors:
            if transistor.electrical:
                v_max_values.append(transistor.electrical.v_abs_max or 0)
                i_max_values.append(transistor.electrical.i_abs_max or 0)
                i_cont_values.append(transistor.electrical.i_cont or 0)
            else:
                v_max_values.append(0)
                i_max_values.append(0)
                i_cont_values.append(0)
        
        return {
            'voltage_max': {
                'values': v_max_values,
                'min': min(v_max_values) if v_max_values else 0,
                'max': max(v_max_values) if v_max_values else 0,
                'avg': sum(v_max_values) / len(v_max_values) if v_max_values else 0
            },
            'current_max': {
                'values': i_max_values,
                'min': min(i_max_values) if i_max_values else 0,
                'max': max(i_max_values) if i_max_values else 0,
                'avg': sum(i_max_values) / len(i_max_values) if i_max_values else 0
            },
            'current_continuous': {
                'values': i_cont_values,
                'min': min(i_cont_values) if i_cont_values else 0,
                'max': max(i_cont_values) if i_cont_values else 0,
                'avg': sum(i_cont_values) / len(i_cont_values) if i_cont_values else 0
            }
        }
    
    def _compare_thermal(self, transistors: List[Transistor]) -> Dict[str, Any]:
        """Compare thermal characteristics."""
        t_j_max_values = []
        r_th_values = []
        
        for transistor in transistors:
            if transistor.thermal:
                t_j_max_values.append(transistor.thermal.t_j_max or 150)
                r_th_values.append(transistor.thermal.r_th_cs or 0)
            else:
                t_j_max_values.append(150)
                r_th_values.append(0)
        
        return {
            'junction_temp_max': {
                'values': t_j_max_values,
                'min': min(t_j_max_values) if t_j_max_values else 0,
                'max': max(t_j_max_values) if t_j_max_values else 0,
                'avg': sum(t_j_max_values) / len(t_j_max_values) if t_j_max_values else 0
            },
            'thermal_resistance': {
                'values': r_th_values,
                'min': min(r_th_values) if r_th_values else 0,
                'max': max(r_th_values) if r_th_values else 0,
                'avg': sum(r_th_values) / len(r_th_values) if r_th_values else 0
            }
        }
    
    def _compare_metadata(self, transistors: List[Transistor]) -> Dict[str, Any]:
        """Compare metadata."""
        types = set()
        manufacturers = set()
        housing_types = set()
        
        for transistor in transistors:
            if transistor.metadata:
                if transistor.metadata.type:
                    types.add(transistor.metadata.type)
                if transistor.metadata.manufacturer:
                    manufacturers.add(transistor.metadata.manufacturer)
                if transistor.metadata.housing_type:
                    housing_types.add(transistor.metadata.housing_type)
        
        return {
            'types': list(types),
            'manufacturers': list(manufacturers),
            'housing_types': list(housing_types),
            'type_distribution': {t: sum(1 for tr in transistors 
                                      if tr.metadata and tr.metadata.type == t) 
                                 for t in types},
            'manufacturer_distribution': {m: sum(1 for tr in transistors 
                                               if tr.metadata and tr.metadata.manufacturer == m) 
                                        for m in manufacturers}
        }
    
    def find_similar_transistors(self, target: Transistor, 
                                candidates: List[Transistor],
                                tolerance: float = 0.1) -> List[Transistor]:
        """Find transistors similar to target."""
        similar = []
        
        if not target.electrical:
            return similar
        
        target_v = target.electrical.v_abs_max or 0
        target_i = target.electrical.i_abs_max or 0
        
        for candidate in candidates:
            if candidate == target or not candidate.electrical:
                continue
            
            cand_v = candidate.electrical.v_abs_max or 0
            cand_i = candidate.electrical.i_abs_max or 0
            
            # Calculate relative differences
            v_diff = abs(cand_v - target_v) / max(target_v, 1)
            i_diff = abs(cand_i - target_i) / max(target_i, 1)
            
            # Check if within tolerance
            if v_diff <= tolerance and i_diff <= tolerance:
                similar.append(candidate)
        
        # Sort by similarity (smaller differences first)
        similar.sort(key=lambda t: (
            abs((t.electrical.v_abs_max or 0) - target_v) / max(target_v, 1) +
            abs((t.electrical.i_abs_max or 0) - target_i) / max(target_i, 1)
        ))
        
        return similar


class ValidationService(IValidationService):
    """Service for validating transistor data."""
    
    def validate_transistor(self, transistor: Transistor) -> Dict[str, List[str]]:
        """Validate complete transistor data."""
        errors = []
        warnings = []
        
        # Validate metadata
        meta_result = self.validate_metadata(transistor.metadata)
        errors.extend(meta_result['errors'])
        warnings.extend(meta_result['warnings'])
        
        # Validate electrical
        elec_result = self.validate_electrical(transistor.electrical)
        errors.extend(elec_result['errors'])
        warnings.extend(elec_result['warnings'])
        
        # Validate thermal
        thermal_result = self.validate_thermal(transistor.thermal)
        errors.extend(thermal_result['errors'])
        warnings.extend(thermal_result['warnings'])
        
        # Cross-validation
        cross_result = self._cross_validate(transistor)
        errors.extend(cross_result['errors'])
        warnings.extend(cross_result['warnings'])
        
        return {
            'errors': errors,
            'warnings': warnings
        }
    
    def validate_metadata(self, metadata) -> Dict[str, List[str]]:
        """Validate transistor metadata."""
        errors = []
        warnings = []
        
        if not metadata:
            errors.append("Metadata is required")
            return {'errors': errors, 'warnings': warnings}
        
        # Check required fields
        if not metadata.name or not metadata.name.strip():
            errors.append("Transistor name is required")
        
        if not metadata.type:
            warnings.append("Transistor type is not specified")
        elif metadata.type not in ['IGBT', 'MOSFET', 'SiC-MOSFET', 'GaN-Transistor', 'Diode']:
            warnings.append(f"Unusual transistor type: {metadata.type}")
        
        if not metadata.manufacturer:
            warnings.append("Manufacturer is not specified")
        
        # Check name format
        if metadata.name and len(metadata.name) > 100:
            warnings.append("Transistor name is very long")
        
        return {'errors': errors, 'warnings': warnings}
    
    def validate_electrical(self, electrical) -> Dict[str, List[str]]:
        """Validate electrical ratings."""
        errors = []
        warnings = []
        
        if not electrical:
            warnings.append("Electrical ratings are not specified")
            return {'errors': errors, 'warnings': warnings}
        
        # Validate voltage
        if electrical.v_abs_max is not None:
            if electrical.v_abs_max <= 0:
                errors.append("Maximum voltage must be positive")
            elif electrical.v_abs_max < 10:
                warnings.append("Maximum voltage seems very low")
            elif electrical.v_abs_max > 10000:
                warnings.append("Maximum voltage seems very high")
        
        # Validate current
        if electrical.i_abs_max is not None:
            if electrical.i_abs_max <= 0:
                errors.append("Maximum current must be positive")
            elif electrical.i_abs_max < 0.1:
                warnings.append("Maximum current seems very low")
            elif electrical.i_abs_max > 1000:
                warnings.append("Maximum current seems very high")
        
        # Validate continuous vs maximum current
        if (electrical.i_cont is not None and electrical.i_abs_max is not None 
            and electrical.i_cont > electrical.i_abs_max):
            errors.append("Continuous current cannot exceed maximum current")
        
        return {'errors': errors, 'warnings': warnings}
    
    def validate_thermal(self, thermal) -> Dict[str, List[str]]:
        """Validate thermal properties."""
        errors = []
        warnings = []
        
        if not thermal:
            warnings.append("Thermal properties are not specified")
            return {'errors': errors, 'warnings': warnings}
        
        # Validate junction temperature
        if thermal.t_j_max is not None:
            if thermal.t_j_max < -50:
                errors.append("Maximum junction temperature is unrealistically low")
            elif thermal.t_j_max > 300:
                errors.append("Maximum junction temperature is unrealistically high")
            elif thermal.t_j_max < 100:
                warnings.append("Maximum junction temperature seems low")
        
        # Validate thermal resistance
        if thermal.r_th_cs is not None:
            if thermal.r_th_cs < 0:
                errors.append("Thermal resistance cannot be negative")
            elif thermal.r_th_cs > 10:
                warnings.append("Thermal resistance seems very high")
        
        return {'errors': errors, 'warnings': warnings}
    
    def _cross_validate(self, transistor: Transistor) -> Dict[str, List[str]]:
        """Cross-validate between different properties."""
        errors = []
        warnings = []
        
        # Check consistency between type and electrical ratings
        if (transistor.metadata and transistor.metadata.type == 'Diode' 
            and transistor.electrical):
            if transistor.electrical.i_cont and transistor.electrical.i_abs_max:
                if transistor.electrical.i_cont > transistor.electrical.i_abs_max * 0.8:
                    warnings.append("Continuous current is high relative to maximum for a diode")
        
        # Check power handling vs thermal properties
        if (transistor.electrical and transistor.thermal 
            and transistor.electrical.v_abs_max and transistor.electrical.i_abs_max
            and transistor.thermal.r_th_cs):
            max_power = transistor.electrical.v_abs_max * transistor.electrical.i_abs_max
            if max_power > 1000 and transistor.thermal.r_th_cs > 1:
                warnings.append("High power device with high thermal resistance")
        
        return {'errors': errors, 'warnings': warnings}
    
    def check_data_completeness(self, transistor: Transistor) -> Dict[str, Any]:
        """Check how complete the transistor data is."""
        completeness = {
            'metadata': 0,
            'electrical': 0,
            'thermal': 0,
            'switch_data': 0,
            'diode_data': 0,
            'overall': 0
        }
        
        # Check metadata completeness
        if transistor.metadata:
            meta_fields = ['name', 'type', 'manufacturer', 'housing_type', 'author']
            filled = sum(1 for field in meta_fields 
                        if getattr(transistor.metadata, field, None))
            completeness['metadata'] = filled / len(meta_fields) * 100
        
        # Check electrical completeness
        if transistor.electrical:
            elec_fields = ['v_abs_max', 'i_abs_max', 'i_cont']
            filled = sum(1 for field in elec_fields 
                        if getattr(transistor.electrical, field, None) is not None)
            completeness['electrical'] = filled / len(elec_fields) * 100
        
        # Check thermal completeness
        if transistor.thermal:
            thermal_fields = ['t_j_max', 'r_th_cs']
            filled = sum(1 for field in thermal_fields 
                        if getattr(transistor.thermal, field, None) is not None)
            completeness['thermal'] = filled / len(thermal_fields) * 100
        
        # Check switch data
        if transistor.switch:
            completeness['switch_data'] = 100 if transistor.switch.channel else 50
        
        # Check diode data
        if transistor.diode:
            completeness['diode_data'] = 100 if transistor.diode.channel else 50
        
        # Calculate overall completeness
        scores = [completeness['metadata'], completeness['electrical'], 
                 completeness['thermal']]
        completeness['overall'] = sum(scores) / len(scores)
        
        return completeness


# Factory for creating concrete services
class ConcreteServiceFactory:
    """Factory for creating concrete service implementations."""
    
    @staticmethod
    def create_plotting_service() -> IPlottingService:
        """Create plotting service."""
        from transistordatabase.backend.services import PlottingService
        return PlottingService()
    
    @staticmethod
    def create_calculation_service() -> ICalculationService:
        """Create calculation service."""
        from transistordatabase.backend.services import CalculationService
        return CalculationService()
    
    @staticmethod
    def create_export_service() -> IExportService:
        """Create export service."""
        return ExportService()
    
    @staticmethod
    def create_comparison_service() -> IComparisonService:
        """Create comparison service."""
        return ComparisonService()
    
    @staticmethod
    def create_validation_service() -> IValidationService:
        """Create validation service."""
        return ValidationService()
    
    @staticmethod
    def create_all_services() -> Dict[str, Any]:
        """Create all services."""
        return {
            'plotting': ConcreteServiceFactory.create_plotting_service(),
            'calculation': ConcreteServiceFactory.create_calculation_service(),
            'export': ConcreteServiceFactory.create_export_service(),
            'comparison': ConcreteServiceFactory.create_comparison_service(),
            'validation': ConcreteServiceFactory.create_validation_service()
        }
